services:
  dsccontas:
    build: .
    container_name: dsccontas
    restart: unless-stopped
    ports:
      - "3010:3010"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3010