services:
  dsccontas:
    build: .
    container_name: dsccontas
    restart: unless-stopped
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
      - AI_BASE_URL=http://192.168.1.158:11434
      - AI_MODEL=qwen2.5:3b
    volumes:
      - ./.env:/app/.env:ro